// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: snakebite_message.proto
#ifndef GRPC_snakebite_5fmessage_2eproto__INCLUDED
#define GRPC_snakebite_5fmessage_2eproto__INCLUDED

#include "snakebite_message.pb.h"

#include <boost/asio.hpp>
#include <acoross/rpc/rpc_service.h>
#include <acoross/rpc/rpc_stub.h>
#include <acoross/rpc/rpc_macros.h>
namespace acoross {
namespace snakebite {
namespace messages {

class Greeter GRPC_FINAL {
 public:
  enum Protocol
  {
    SayHello,
  }
  class Service : public ::acoross::rpc::RpcService 
  { public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::acoross::snakebite::messages::HelloRequest& request, ::acoross::snakebite::messages::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::acoross::snakebite::messages::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::acoross::snakebite::messages::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::acoross::snakebite::messages::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::acoross::snakebite::messages::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::acoross::snakebite::messages::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::acoross::snakebite::messages::HelloRequest& request, ::acoross::snakebite::messages::HelloReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::acoross::snakebite::messages::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::acoross::snakebite::messages::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::acoross::snakebite::messages::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::acoross::snakebite::messages::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::acoross::snakebite::messages::HelloRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_SayHello_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::acoross::snakebite::messages::HelloRequest* request, ::acoross::snakebite::messages::HelloReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(Service *service) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* context, const ::acoross::snakebite::messages::HelloRequest* request, ::acoross::snakebite::messages::HelloReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::acoross::snakebite::messages::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::acoross::snakebite::messages::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(Service *service) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* context, const ::acoross::snakebite::messages::HelloRequest* request, ::acoross::snakebite::messages::HelloReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace messages
}  // namespace snakebite
}  // namespace acoross


#endif  // GRPC_snakebite_5fmessage_2eproto__INCLUDED
