#ifndef SNAKEBITE_MOVING_OBJECT_SYSTEM_MOVING_OBJECT_SYSTEM_H_
#define SNAKEBITE_MOVING_OBJECT_SYSTEM_MOVING_OBJECT_SYSTEM_H_

#include "details/geo_types.h"
#include "details/moving_object.h"

#endif //SNAKEBITE_MOVING_OBJECT_SYSTEM_MOVING_OBJECT_SYSTEM_H_