// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sc_snakebite_message.proto

#ifndef PROTOBUF_sc_5fsnakebite_5fmessage_2eproto__INCLUDED
#define PROTOBUF_sc_5fsnakebite_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace acoross {
namespace snakebite {
namespace sc_messages {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_sc_5fsnakebite_5fmessage_2eproto();
void protobuf_AssignDesc_sc_5fsnakebite_5fmessage_2eproto();
void protobuf_ShutdownFile_sc_5fsnakebite_5fmessage_2eproto();

class GameObjectClone;
class MovingObject;
class UpdateGameObjects;

// ===================================================================

class MovingObject : public ::google::protobuf::Message {
 public:
  MovingObject();
  virtual ~MovingObject();

  MovingObject(const MovingObject& from);

  inline MovingObject& operator=(const MovingObject& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MovingObject& default_instance();

  void Swap(MovingObject* other);

  // implements Message ----------------------------------------------

  inline MovingObject* New() const { return New(NULL); }

  MovingObject* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MovingObject& from);
  void MergeFrom(const MovingObject& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MovingObject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double radius = 3;
  void clear_radius();
  static const int kRadiusFieldNumber = 3;
  double radius() const;
  void set_radius(double value);

  // @@protoc_insertion_point(class_scope:acoross.snakebite.sc_messages.MovingObject)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double x_;
  double y_;
  double radius_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sc_5fsnakebite_5fmessage_2eproto();
  friend void protobuf_AssignDesc_sc_5fsnakebite_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_sc_5fsnakebite_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static MovingObject* default_instance_;
};
// -------------------------------------------------------------------

class GameObjectClone : public ::google::protobuf::Message {
 public:
  GameObjectClone();
  virtual ~GameObjectClone();

  GameObjectClone(const GameObjectClone& from);

  inline GameObjectClone& operator=(const GameObjectClone& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameObjectClone& default_instance();

  void Swap(GameObjectClone* other);

  // implements Message ----------------------------------------------

  inline GameObjectClone* New() const { return New(NULL); }

  GameObjectClone* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameObjectClone& from);
  void MergeFrom(const GameObjectClone& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GameObjectClone* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 clone_type = 1;
  void clear_clone_type();
  static const int kCloneTypeFieldNumber = 1;
  ::google::protobuf::int32 clone_type() const;
  void set_clone_type(::google::protobuf::int32 value);

  // optional int64 handle = 2;
  void clear_handle();
  static const int kHandleFieldNumber = 2;
  ::google::protobuf::int64 handle() const;
  void set_handle(::google::protobuf::int64 value);

  // optional .acoross.snakebite.sc_messages.MovingObject head = 3;
  bool has_head() const;
  void clear_head();
  static const int kHeadFieldNumber = 3;
  const ::acoross::snakebite::sc_messages::MovingObject& head() const;
  ::acoross::snakebite::sc_messages::MovingObject* mutable_head();
  ::acoross::snakebite::sc_messages::MovingObject* release_head();
  void set_allocated_head(::acoross::snakebite::sc_messages::MovingObject* head);

  // optional int32 body_count = 4;
  void clear_body_count();
  static const int kBodyCountFieldNumber = 4;
  ::google::protobuf::int32 body_count() const;
  void set_body_count(::google::protobuf::int32 value);

  // repeated .acoross.snakebite.sc_messages.MovingObject body = 5;
  int body_size() const;
  void clear_body();
  static const int kBodyFieldNumber = 5;
  const ::acoross::snakebite::sc_messages::MovingObject& body(int index) const;
  ::acoross::snakebite::sc_messages::MovingObject* mutable_body(int index);
  ::acoross::snakebite::sc_messages::MovingObject* add_body();
  ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::MovingObject >*
      mutable_body();
  const ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::MovingObject >&
      body() const;

  // @@protoc_insertion_point(class_scope:acoross.snakebite.sc_messages.GameObjectClone)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 handle_;
  ::google::protobuf::int32 clone_type_;
  ::google::protobuf::int32 body_count_;
  ::acoross::snakebite::sc_messages::MovingObject* head_;
  ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::MovingObject > body_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sc_5fsnakebite_5fmessage_2eproto();
  friend void protobuf_AssignDesc_sc_5fsnakebite_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_sc_5fsnakebite_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static GameObjectClone* default_instance_;
};
// -------------------------------------------------------------------

class UpdateGameObjects : public ::google::protobuf::Message {
 public:
  UpdateGameObjects();
  virtual ~UpdateGameObjects();

  UpdateGameObjects(const UpdateGameObjects& from);

  inline UpdateGameObjects& operator=(const UpdateGameObjects& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateGameObjects& default_instance();

  void Swap(UpdateGameObjects* other);

  // implements Message ----------------------------------------------

  inline UpdateGameObjects* New() const { return New(NULL); }

  UpdateGameObjects* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateGameObjects& from);
  void MergeFrom(const UpdateGameObjects& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateGameObjects* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 clone_count = 1;
  void clear_clone_count();
  static const int kCloneCountFieldNumber = 1;
  ::google::protobuf::int32 clone_count() const;
  void set_clone_count(::google::protobuf::int32 value);

  // repeated .acoross.snakebite.sc_messages.GameObjectClone clone = 2;
  int clone_size() const;
  void clear_clone();
  static const int kCloneFieldNumber = 2;
  const ::acoross::snakebite::sc_messages::GameObjectClone& clone(int index) const;
  ::acoross::snakebite::sc_messages::GameObjectClone* mutable_clone(int index);
  ::acoross::snakebite::sc_messages::GameObjectClone* add_clone();
  ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::GameObjectClone >*
      mutable_clone();
  const ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::GameObjectClone >&
      clone() const;

  // @@protoc_insertion_point(class_scope:acoross.snakebite.sc_messages.UpdateGameObjects)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::GameObjectClone > clone_;
  ::google::protobuf::int32 clone_count_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sc_5fsnakebite_5fmessage_2eproto();
  friend void protobuf_AssignDesc_sc_5fsnakebite_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_sc_5fsnakebite_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static UpdateGameObjects* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MovingObject

// optional double x = 1;
inline void MovingObject::clear_x() {
  x_ = 0;
}
inline double MovingObject::x() const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.MovingObject.x)
  return x_;
}
inline void MovingObject::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:acoross.snakebite.sc_messages.MovingObject.x)
}

// optional double y = 2;
inline void MovingObject::clear_y() {
  y_ = 0;
}
inline double MovingObject::y() const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.MovingObject.y)
  return y_;
}
inline void MovingObject::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:acoross.snakebite.sc_messages.MovingObject.y)
}

// optional double radius = 3;
inline void MovingObject::clear_radius() {
  radius_ = 0;
}
inline double MovingObject::radius() const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.MovingObject.radius)
  return radius_;
}
inline void MovingObject::set_radius(double value) {
  
  radius_ = value;
  // @@protoc_insertion_point(field_set:acoross.snakebite.sc_messages.MovingObject.radius)
}

// -------------------------------------------------------------------

// GameObjectClone

// optional int32 clone_type = 1;
inline void GameObjectClone::clear_clone_type() {
  clone_type_ = 0;
}
inline ::google::protobuf::int32 GameObjectClone::clone_type() const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.GameObjectClone.clone_type)
  return clone_type_;
}
inline void GameObjectClone::set_clone_type(::google::protobuf::int32 value) {
  
  clone_type_ = value;
  // @@protoc_insertion_point(field_set:acoross.snakebite.sc_messages.GameObjectClone.clone_type)
}

// optional int64 handle = 2;
inline void GameObjectClone::clear_handle() {
  handle_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GameObjectClone::handle() const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.GameObjectClone.handle)
  return handle_;
}
inline void GameObjectClone::set_handle(::google::protobuf::int64 value) {
  
  handle_ = value;
  // @@protoc_insertion_point(field_set:acoross.snakebite.sc_messages.GameObjectClone.handle)
}

// optional .acoross.snakebite.sc_messages.MovingObject head = 3;
inline bool GameObjectClone::has_head() const {
  return !_is_default_instance_ && head_ != NULL;
}
inline void GameObjectClone::clear_head() {
  if (GetArenaNoVirtual() == NULL && head_ != NULL) delete head_;
  head_ = NULL;
}
inline const ::acoross::snakebite::sc_messages::MovingObject& GameObjectClone::head() const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.GameObjectClone.head)
  return head_ != NULL ? *head_ : *default_instance_->head_;
}
inline ::acoross::snakebite::sc_messages::MovingObject* GameObjectClone::mutable_head() {
  
  if (head_ == NULL) {
    head_ = new ::acoross::snakebite::sc_messages::MovingObject;
  }
  // @@protoc_insertion_point(field_mutable:acoross.snakebite.sc_messages.GameObjectClone.head)
  return head_;
}
inline ::acoross::snakebite::sc_messages::MovingObject* GameObjectClone::release_head() {
  
  ::acoross::snakebite::sc_messages::MovingObject* temp = head_;
  head_ = NULL;
  return temp;
}
inline void GameObjectClone::set_allocated_head(::acoross::snakebite::sc_messages::MovingObject* head) {
  delete head_;
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:acoross.snakebite.sc_messages.GameObjectClone.head)
}

// optional int32 body_count = 4;
inline void GameObjectClone::clear_body_count() {
  body_count_ = 0;
}
inline ::google::protobuf::int32 GameObjectClone::body_count() const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.GameObjectClone.body_count)
  return body_count_;
}
inline void GameObjectClone::set_body_count(::google::protobuf::int32 value) {
  
  body_count_ = value;
  // @@protoc_insertion_point(field_set:acoross.snakebite.sc_messages.GameObjectClone.body_count)
}

// repeated .acoross.snakebite.sc_messages.MovingObject body = 5;
inline int GameObjectClone::body_size() const {
  return body_.size();
}
inline void GameObjectClone::clear_body() {
  body_.Clear();
}
inline const ::acoross::snakebite::sc_messages::MovingObject& GameObjectClone::body(int index) const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.GameObjectClone.body)
  return body_.Get(index);
}
inline ::acoross::snakebite::sc_messages::MovingObject* GameObjectClone::mutable_body(int index) {
  // @@protoc_insertion_point(field_mutable:acoross.snakebite.sc_messages.GameObjectClone.body)
  return body_.Mutable(index);
}
inline ::acoross::snakebite::sc_messages::MovingObject* GameObjectClone::add_body() {
  // @@protoc_insertion_point(field_add:acoross.snakebite.sc_messages.GameObjectClone.body)
  return body_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::MovingObject >*
GameObjectClone::mutable_body() {
  // @@protoc_insertion_point(field_mutable_list:acoross.snakebite.sc_messages.GameObjectClone.body)
  return &body_;
}
inline const ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::MovingObject >&
GameObjectClone::body() const {
  // @@protoc_insertion_point(field_list:acoross.snakebite.sc_messages.GameObjectClone.body)
  return body_;
}

// -------------------------------------------------------------------

// UpdateGameObjects

// optional int32 clone_count = 1;
inline void UpdateGameObjects::clear_clone_count() {
  clone_count_ = 0;
}
inline ::google::protobuf::int32 UpdateGameObjects::clone_count() const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.UpdateGameObjects.clone_count)
  return clone_count_;
}
inline void UpdateGameObjects::set_clone_count(::google::protobuf::int32 value) {
  
  clone_count_ = value;
  // @@protoc_insertion_point(field_set:acoross.snakebite.sc_messages.UpdateGameObjects.clone_count)
}

// repeated .acoross.snakebite.sc_messages.GameObjectClone clone = 2;
inline int UpdateGameObjects::clone_size() const {
  return clone_.size();
}
inline void UpdateGameObjects::clear_clone() {
  clone_.Clear();
}
inline const ::acoross::snakebite::sc_messages::GameObjectClone& UpdateGameObjects::clone(int index) const {
  // @@protoc_insertion_point(field_get:acoross.snakebite.sc_messages.UpdateGameObjects.clone)
  return clone_.Get(index);
}
inline ::acoross::snakebite::sc_messages::GameObjectClone* UpdateGameObjects::mutable_clone(int index) {
  // @@protoc_insertion_point(field_mutable:acoross.snakebite.sc_messages.UpdateGameObjects.clone)
  return clone_.Mutable(index);
}
inline ::acoross::snakebite::sc_messages::GameObjectClone* UpdateGameObjects::add_clone() {
  // @@protoc_insertion_point(field_add:acoross.snakebite.sc_messages.UpdateGameObjects.clone)
  return clone_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::GameObjectClone >*
UpdateGameObjects::mutable_clone() {
  // @@protoc_insertion_point(field_mutable_list:acoross.snakebite.sc_messages.UpdateGameObjects.clone)
  return &clone_;
}
inline const ::google::protobuf::RepeatedPtrField< ::acoross::snakebite::sc_messages::GameObjectClone >&
UpdateGameObjects::clone() const {
  // @@protoc_insertion_point(field_list:acoross.snakebite.sc_messages.UpdateGameObjects.clone)
  return clone_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sc_messages
}  // namespace snakebite
}  // namespace acoross

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sc_5fsnakebite_5fmessage_2eproto__INCLUDED
