// Generated by the acoross-rpc protobuf plugin.
// If you make any local change, they will be lost.
// source: snakebite_message.proto

#include "snakebite_message.pb.h"
#include "snakebite_message.rpc.h"

namespace acoross {
namespace snakebite {
namespace messages {

MyRpc::Service::Service(::boost::asio::io_service& io_service, ::boost::asio::ip::tcp::socket&& socket)
	: ::acoross::rpc::RpcService(io_service, std::move(socket))
{
  REGISTER_SERVICE(Hello, ::acoross::snakebite::messages::HelloRequest, ::acoross::snakebite::messages::HelloReply)
  REGISTER_SERVICE(TurnKeyDown, ::acoross::snakebite::messages::TurnKeyDownRequest, ::acoross::snakebite::messages::VoidReply)
  REGISTER_SERVICE(TurnKeyUp, ::acoross::snakebite::messages::TurnKeyUpRequest, ::acoross::snakebite::messages::VoidReply)
}

MyRpc::Stub::Stub(::boost::asio::io_service& io_service, ::boost::asio::ip::tcp::socket&& socket)
	: ::acoross::rpc::RpcStub(io_service, std::move(socket))
{}


}  // namespace acoross
}  // namespace snakebite
}  // namespace messages

