// Generated by the acoross-rpc protobuf plugin.
// If you make any local change, they will be lost.
// source: test_rpc.proto

#include "test_rpc.pb.h"
#include "test_rpc.rpc.h"

namespace acoross {
namespace rpc_test {

TestRpc::Service::Service(::boost::asio::io_service& io_service, ::boost::asio::ip::tcp::socket&& socket)
	: ::acoross::rpc::RpcService(io_service, std::move(socket))
{
  REGISTER_SERVICE(Hello, ::acoross::rpc_test::HelloRequest, ::acoross::rpc_test::HelloReply)
}

TestRpc::Stub::Stub(::boost::asio::io_service& io_service, ::boost::asio::ip::tcp::socket&& socket)
	: ::acoross::rpc::RpcStub(io_service, std::move(socket))
{}


}  // namespace acoross
}  // namespace rpc_test

