// Generated by the acoross-rpc protobuf plugin.
// If you make any local change, they will be lost.
// source: test_rpc.proto
#ifndef ACOROSS_RPC_test_5frpc_2eproto__INCLUDED
#define ACOROSS_RPC_test_5frpc_2eproto__INCLUDED

#include "test_rpc.pb.h"

#include <SDKDDKVer.h>
#include <boost/asio.hpp>
#include <acoross/rpc/rpc_service.h>
#include <acoross/rpc/rpc_stub.h>
#include <acoross/rpc/rpc_macros.h>

namespace acoross {
namespace rpc_test {

class TestRpc final {
 public:
  enum Protocol
  {
    Hello,
  };

  class Service : public ::acoross::rpc::RpcService 
  {
  public:
    Service(::boost::asio::io_service& io_service, ::boost::asio::ip::tcp::socket&& socket);
    virtual ~Service() {}

  private:
    DEF_SERVICE(Hello, ::acoross::rpc_test::HelloRequest, ::acoross::rpc_test::HelloReply)

  };

  class Stub : public ::acoross::rpc::RpcStub
  {
  public:
    Stub(::boost::asio::io_service& io_service, ::boost::asio::ip::tcp::socket&& socket);
    virtual ~Stub() {}
    DEF_STUB(Hello, ::acoross::rpc_test::HelloRequest, ::acoross::rpc_test::HelloReply)
  };

};


}  // namespace rpc_test
}  // namespace acoross


#endif  // ACOROSS_RPC_test_5frpc_2eproto__INCLUDED
